using DataAnalyzer.ApplicationConfigurations.DataConfigurations.ClassSetupConfigurations;

namespace DataAnalyzer.Models.DataStructureSetupModels;

internal interface IClassCreationSetupModel : IDataStructureSetupModel<ClassCollectionSetupConfiguration>
{
}
