using ExcelService.DataActions.ActionParameters.RangeStyleParameters;

namespace ExcelService.DataActions.ActionParameters.ClusterHeaderStyleParameters;

public interface IHeaderBackgroundStyleParameters : IBackgroundStyleParameters
{
}