namespace DataAnalyzer.ViewModels.ExcelSetupViewModels.ExcelActionViewModels.ExcelSpecificationViewModels.Application;

internal interface IRowActionApplicationViewModel : IActionApplicationViewModel
{
}
