namespace DataAnalyzer.ViewModels.ExcelSetupViewModels.ExcelActionViewModels.ExcelSpecificationViewModels.Creation;

internal interface IWorksheetActionCreationViewModel : IActionCreationViewModel
{
}
