//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnalyzer.Properties; 


[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
    
    private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
    
    public static Settings Default {
        get {
            return defaultInstance;
        }
    }
    
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string LastUsedDataDirectory {
        get {
            return ((string)(this["LastUsedDataDirectory"]));
        }
        set {
            this["LastUsedDataDirectory"] = value;
        }
    }
    
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string LastSelectedScraperType {
        get {
            return ((string)(this["LastSelectedScraperType"]));
        }
        set {
            this["LastSelectedScraperType"] = value;
        }
    }
    
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string LastUsedExcelConfigurationDirectory {
        get {
            return ((string)(this["LastUsedExcelConfigurationDirectory"]));
        }
        set {
            this["LastUsedExcelConfigurationDirectory"] = value;
        }
    }
    
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string LastUsedExcelOutputDirectory {
        get {
            return ((string)(this["LastUsedExcelOutputDirectory"]));
        }
        set {
            this["LastUsedExcelOutputDirectory"] = value;
        }
    }
    
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string LastUsedClassCreationConfigurationDirectory {
        get {
            return ((string)(this["LastUsedClassCreationConfigurationDirectory"]));
        }
        set {
            this["LastUsedClassCreationConfigurationDirectory"] = value;
        }
    }
    
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string LastUsedApplicationRootDirectory {
        get {
            return ((string)(this["LastUsedApplicationRootDirectory"]));
        }
        set {
            this["LastUsedApplicationRootDirectory"] = value;
        }
    }
    
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string LastUsedApplicationConfigurationName {
        get {
            return ((string)(this["LastUsedApplicationConfigurationName"]));
        }
        set {
            this["LastUsedApplicationConfigurationName"] = value;
        }
    }
}
