using DataAnalyzer.ApplicationConfigurations;
using DataAnalyzer.Common.DataParameters;
using DataAnalyzer.Common.Mvvm;
using DataAnalyzer.Models.ImportModels;
using DataAnalyzer.Services;
using DataAnalyzer.Services.Enums;
using DataAnalyzer.StatConfigurations;
using DataScraper.DataScrapers.ImportTypes;
using DataScraper.DataScrapers.ScraperCategories;
using DataScraper.DataScrapers.ScraperFlavors;
using System;
using System.Collections.Generic;
using System.IO;

namespace DataAnalyzer.Models
{
    internal class ConfigurationModel : BasePropertyChanged
    {
        private static string FILE_IMPORT_DIRECTORY = "FileImport";
        private static string FILE_IMPORT_MAPPING_FILE = "DirectoryMappings.json";

        private readonly SerializationService serializer = new();

        // TODO --> I feel like these two don't belong here
        private readonly DataParameterLibrary dataParameterLibrary = new();
        private IDataParameterCollection dataParameterCollection = null;

        // These fields are set on page zero and allow the user to have different application configurations
        // This can help compartmentalize if the application grows to be large
        private string configurationDirectory = string.Empty;
        private string configurationName = "MyAppConfig";
        private string configurationFilePath = string.Empty;

        private string executiveConfigurationDirectory = string.Empty;
        private string executiveConfigurationName= string.Empty;

        private IImportType importType = null;
        private IScraperCategory category = null;
        private IScraperFlavor flavor = null;
        private IDataConfiguration dataConfiguration = new NotSupportedDataConfiguration();
        private ExportType selectedExportType = ExportType.NotApplicable;
        private ImportExportKey importExportKey = ImportExportKey.Default;

        // This refers to where data configurations are stored which is an autogenerated path based on the others, so this is OBE
        private string savedDataFilePath = string.Empty;

        public ConfigurationModel()
        {
            this.ConfigurationDirectory = Properties.Settings.Default.LastUsedApplicationRootDirectory;
            this.ConfigurationName = Properties.Settings.Default.LastUsedApplicationConfigurationName;
            this.LoadConfiguration();

            // TODO --> this should have a save/apply method
            // TODO --> main model should be updating this guy with import/category/flavor/export (the properties don't need to be here)
            // TODO --> make sure to handle partially set types
        }

        public ImportExportKey ImportExportKey
        {
            get => this.importExportKey;
            set
            {
                if (value == null)
                {
                    string str = "hello";
                }
                this.NotifyPropertyChanged(ref this.importExportKey, value);

                // TODO --> the library needs to support import/category/flavor/export
                //this.DataParameterCollection = this.dataParameterLibrary.GetParameters(StatType.NotApplicable);
            }
        }

        public ExportType SelectedExportType
        {
            get => this.selectedExportType;
            set
            {
                this.ImportExportKey.Update(value);
                this.NotifyPropertyChanged(nameof(this.ImportExportKey));
                this.NotifyPropertyChanged(ref this.selectedExportType, value);
            }
        }

        public IImportType ImportType
        {
            get => this.importType;
            set
            {
                this.ImportExportKey.Update(value);
                this.NotifyPropertyChanged(nameof(this.ImportExportKey));
                this.NotifyPropertyChanged(ref this.importType, value);
            }
        }

        public IScraperCategory Category
        {
            get => this.category;
            set
            {
                this.ImportExportKey.Update(value);
                this.NotifyPropertyChanged(nameof(this.ImportExportKey));
                this.NotifyPropertyChanged(ref this.category, value);
            }
        }

        public IScraperFlavor Flavor
        {
            get => this.flavor;
            set
            {
                this.ImportExportKey.Update(value);
                this.NotifyPropertyChanged(nameof(this.ImportExportKey));
                this.NotifyPropertyChanged(ref this.flavor, value);
            }
        }

        public IDataConfiguration DataConfiguration
        {
            get => this.dataConfiguration;
            set => this.NotifyPropertyChanged(ref this.dataConfiguration, value);
        }

        // TODO --> should this actually be in this location? Maybe keep it in the stats model instead
        public IDataParameterCollection DataParameterCollection
        {
            get => this.dataParameterCollection;
            set => this.NotifyPropertyChanged(ref this.dataParameterCollection, value);
        }

        /// <summary>
        /// Location where last-application-state will be stored
        /// </summary>
        public string ConfigurationDirectory
        {
            get => this.configurationDirectory;
            set
            {
                this.NotifyPropertyChanged(ref this.configurationDirectory, value);

                Properties.Settings.Default.LastUsedApplicationRootDirectory = value;
                Properties.Settings.Default.Save();
                this.ApplyFilePath();
            }
        }

        /// <summary>
        /// Location where the import/export combination's configuration is stored
        /// </summary>
        public string ExecutiveConfigurationDirectory
        {
            get => this.executiveConfigurationDirectory;
            set => this.NotifyPropertyChanged(ref this.executiveConfigurationDirectory, value);
        }


        /// <summary>
        /// Name of last-application-state file
        /// </summary>
        public string ConfigurationName
        {
            get => this.configurationName;
            set
            {
                this.NotifyPropertyChanged(ref this.configurationName, value);
                Properties.Settings.Default.LastUsedApplicationConfigurationName = value;
                Properties.Settings.Default.Save();
                this.ApplyFilePath();
            }
        }

        /// <summary>
        /// Name of the import/export combination's configuration
        /// </summary>
        public string ExecutiveConfigurationName
        {
            get => this.executiveConfigurationName;
            set => this.NotifyPropertyChanged(ref this.executiveConfigurationName, value);
        }

        public string ConfigurationFilePath
        {
            get => this.configurationFilePath;
            set => this.NotifyPropertyChanged(ref this.configurationFilePath, value);
        }

        // This refers to where data configurations are stored which is an autogenerated path based on the others, so this is OBE
        public string SavedDataFilePath
        {
            get => this.savedDataFilePath;
            set => this.NotifyPropertyChanged(ref this.savedDataFilePath, value);
        }

        public void ApplyConfiguration(IImportType import, IScraperCategory category, IScraperFlavor flavor)
        {
            this.ImportType = import;
            this.Category = category;
            this.Flavor = flavor;
        }

        public bool HasLoaded { get; private set; } = false;

        public void SaveConfiguration()
        {
            ApplicationConfiguration config = new()
            {
                SelectedImport = this.importType,
                SelectedCategory = this.category,
                SelectedFlavor = this.flavor,
                SelectedExport = this.selectedExportType,
                DateTime = DateTime.Now,
            };

            serializer.JsonSerializeToFile(config, this.configurationFilePath);
        }

        public bool LoadConfiguration()
        {
            try
            {
                ApplicationConfiguration config = serializer.JsonDeserializeFromFile<ApplicationConfiguration>(this.configurationFilePath);
                this.ImportType = config.SelectedImport;
                this.Category = config.SelectedCategory;
                this.Flavor = config.SelectedFlavor;
                this.SelectedExportType = config.SelectedExport;

                this.ImportExportKey = new ImportExportKey(
                    new ImportKey(this.ImportType, this.Category, this.Flavor),
                    this.SelectedExportType);

                // TODO - MAIN -->  I think I need to convert this application configuration to the correct DataConfiguration

                return this.HasLoaded = true;
            }
            catch
            {
                return this.HasLoaded = false;
            }
        }

        public void UpdateFileImportMappings(FileMap fileMap)
        {
            string mappingFile = this.GetFileImportAppConfigPath();
            Directory.CreateDirectory(Path.GetDirectoryName(mappingFile));
            this.serializer.JsonSerializeToFile(fileMap.ToSerializable(), mappingFile);
        }

        public FileMap GetFileImportMappings()
        {
            string mappingFile = this.GetFileImportAppConfigPath();

            if (File.Exists(mappingFile))
            {
                var result = this.serializer.JsonDeserializeFromFile<List<KeyValuePair<IImportType, List<KeyValuePair<IScraperCategory, List<KeyValuePair<IScraperFlavor, string>>>>>>>(mappingFile);
                var fileMap = new FileMap();
                fileMap.FromSerializable(result);
                return fileMap;
            }

            return new FileMap();
        }

        private void ApplyFilePath()
        {
            string filePath = Path.Combine(this.configurationDirectory, this.configurationName);

            if (!filePath.EndsWith(".json"))
            {
                filePath += ".json";
            }

            if (File.Exists(filePath))
            {
                this.ConfigurationFilePath = filePath;
                this.LoadConfiguration();
            }
        }

        private string GetFileImportAppConfigPath()
            => Path.Combine(this.configurationDirectory, FILE_IMPORT_DIRECTORY, FILE_IMPORT_MAPPING_FILE);
    }
}
